### ISSUE TITLE
[Bug] Catch exceptions

### ISSUE THREAD

**Issue by pierotofy** [HeDo88TH/Obj2Tiles#7]
Exceptions that are not captured cause a core dump.

E.g. running out of space causes:

```
Unhandled exception. System.IO.IOException: No space left on device : '/tmp/88eed7c3-0520-419e-804e-c5e1eaed014c-obj2tiles-split'
   at System.IO.FileSystem.CreateDirectory(String )
   at System.IO.Directory.CreateDirectory(String )
   at Obj2Tiles.Program.CreateTempFolder(String folderName) in /home/runner/work/Obj2Tiles/Obj2Tiles/Obj2Tiles/Program.cs:line 199
   at Obj2Tiles.Program.Run(Options opts) in /home/runner/work/Obj2Tiles/Obj2Tiles/Obj2Tiles/Program.cs:line 128
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at Obj2Tiles.Program.Main(String[] args) in /home/runner/work/Obj2Tiles/Obj2Tiles/Obj2Tiles/Program.cs:line 19
   at Obj2Tiles.Program.<Main>(String[] args)
Aborted (core dumped)
```
The program should exit gracefully with error code 1.

**Comment by HeDo88TH** [comment]
Fixed!
